blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/your-repo/your-project/issues/new?template=bug_report.md
    about: Report a bug you've found in the project.
  - name: Feature Request
    url: https://github.com/your-repo/your-project/issues/new?template=feature_request.md
    about: Suggest a new idea for the project.
